# Generated by Django 5.2 on 2025-04-20 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('meal_time', models.CharField(max_length=100)),
                ('meal_location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_calories', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_meal_session',
            },
        ),
        migrations.CreateModel(
            name='MealItemEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitems')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_items', to='users.mealsession')),
            ],
            options={
                'db_table': 'user_meal_items_entries',
            },
        ),
    ]
