# Generated by Django 5.2 on 2025-04-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealsession',
            old_name='date',
            new_name='menu_date',
        ),
    ]
