# Generated by Django 5.2 on 2025-04-20 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_date_mealsession_menu_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealsession',
            old_name='menu_date',
            new_name='date',
        ),
    ]
