# Generated by Django 5.2 on 2025-04-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_menu_date_mealsession_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsession',
            name='date',
            field=models.DateField(),
        ),
    ]
