# Generated by Django 5.2 on 2025-04-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'menu_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItemsAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'menu_items_association',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('meal_time', models.CharField(max_length=100)),
                ('meal_location', models.TextField()),
            ],
            options={
                'db_table': 'menus',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
